[project]
name = "shtns"
version = "3.7.5"
description = "High performance Spherical Harmonic Transform"
authors = [
  { name="Nathanael Schaeffer", email="nathanael.schaeffer@gmail.com" },
]
readme = "README-python.md"
dependencies = [
  'numpy',
]
requires-python = ">=3.2"
classifiers = [
    "Programming Language :: C",
    "Programming Language :: Python",
    "License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)",
    "Intended Audience :: Science/Research",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering",
]
[build-system]
requires = ["setuptools>=61.0", "numpy"]
build-backend = "setuptools.build_meta"
[project.urls]
Homepage = "https://bitbucket.org/nschaeff/shtns/"
Documentation = "https://nschaeff.bitbucket.io/shtns/"
Repository = "https://bitbucket.org/nschaeff/shtns/"
Changelog = "https://bitbucket.org/nschaeff/shtns/src/master/CHANGELOG.md"
