###########################################################
# Authors :
#   - Máté Ferenc Nagy-Egri - 2021
###########################################################

if(NOT DEFINED INPUT_FILE)
	message(FATAL_ERROR "No input file provided using INPUT_FILE")
endif()
if(NOT DEFINED OUTPUT_FILE)
	message(FATAL_ERROR "No output file provided using OUTPUT_FILE")
endif()
if(NOT DEFINED PARITY)
	message(FATAL_ERROR "No parity provided using PARITY")
else()
	if (NOT PARITY MATCHES "(EV|OD|EO)")
		message(FATAL_ERROR "Unkown parity: ${PARITY}")
	endif()
endif()
if(NOT DEFINED COMPONENT)
	message(FATAL_ERROR "No component provided using COMPONENT")
else()
	if (NOT COMPONENT MATCHES "(ST|S|T|Q|QST)")
		message(FATAL_ERROR "Unkown component: ${COMPONENT}")
	endif()
endif()

file(READ ${INPUT_FILE} INTACT_INPUT_STRING)

# Need to blow the string apart into a list, because the CMake regex engine treats
# ^ and $ not line-by-line, but for the entire input. To run regex line-by-line,
# we convert it into a list.
#
# See: https://cmake.cmake.narkive.com/f05xOtbE/regex-and-do-not-match-on-multi-line-input
#
# Unfortunately, this way of traversing a list using will skip empty lines. This
# isn't a dealbreaker in our case (C source files fragments). For the split to work
# we need to pick a character absent from the source file so that statement ending
# semi-colons don't interfere with the list delimiter ; of CMake
set(ABSENT_CHAR "$")
string(REGEX REPLACE ";" ${ABSENT_CHAR} INTACT_INPUT_STRING "${INTACT_INPUT_STRING}")
string(REGEX REPLACE "\n" ";" INPUT_STRINGS "${INTACT_INPUT_STRING}")

set(OUTPUT_LIST)
foreach(INPUT_STRING IN LISTS INPUT_STRINGS)

	# second char : 1BEO
	if(PARITY STREQUAL EV)
		# even (1,E)
		string(REGEX REPLACE "^(.)[1E]" "1" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^.[BO].+\r?" "" INPUT_STRING "${INPUT_STRING}")
	elseif(PARITY STREQUAL OD)
		# odd (1,O)
		string(REGEX REPLACE "^(.)[1O]" "1" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^.[BE].+\r?" "" INPUT_STRING "${INPUT_STRING}")
	elseif(PARITY STREQUAL EO)
		# both (B,E,O)
		string(REGEX REPLACE "^(.)[EOB]" "1" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^.1[^\r\n]+[\r\n]" "" INPUT_STRING "${INPUT_STRING}")
	else()
		message(FATAL_ERROR "Script arg sanitizing failed. Unkown parity requested: ${PARITY}")
	endif()

	# first char : V,Q,S,T
	if(COMPONENT STREQUAL ST)
		# Spheroidal and Toroidal (V,S,T)
		string(REGEX REPLACE "^[3Q#].+\r?" "" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^[VST]X*" "" INPUT_STRING "${INPUT_STRING}")
	elseif(COMPONENT STREQUAL S)
		# Spheroidal component only (V,S)
		string(REGEX REPLACE "^[3QT#].+\r?" "" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^[VS]X*" "" INPUT_STRING "${INPUT_STRING}")
	elseif(COMPONENT STREQUAL T)
		# Toroidal component only (V,T)
		string(REGEX REPLACE "^[3QS#].+\r?" "" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^[VT]X*" "" INPUT_STRING "${INPUT_STRING}")
	elseif(COMPONENT STREQUAL Q)
		# Scalar component (Q)
		string(REGEX REPLACE "^[3VST#].+\r?" "" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^QX*" "" INPUT_STRING "${INPUT_STRING}")
	elseif(COMPONENT STREQUAL QST)
		# 3D Vector component (VQST3) but not exclusive (.X) lines.
		string(REGEX REPLACE "^[#].+\r?" "" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^.X.+\r?" "" INPUT_STRING "${INPUT_STRING}")
		string(REGEX REPLACE "^[QVST3]" "" INPUT_STRING "${INPUT_STRING}")
	else()
		message(FATAL_ERROR "Script arg sanitizing failed. Unkown component requested: ${COMPONENT}")
	endif()

	list(APPEND OUTPUT_LIST ${INPUT_STRING})
endforeach()

list(JOIN OUTPUT_LIST "\n" OUTPUT_STRING)
string(REPLACE ${ABSENT_CHAR} ";" OUTPUT_STRING "${OUTPUT_STRING}")

file(WRITE ${OUTPUT_FILE}
	#"// This file was automatically generated by 'cmake' from file '${INPUT_FILE}'.\n"
	#"// To modify it, please consider modifying ${INPUT_FILE}\n"
	"${OUTPUT_STRING}"
)
